CREATE DATABASE RoyalEducationalAcademyPortal
GO
USE RoyalEducationalAcademyPortal
GO
-- CREATE TABLE MEMBERPERMISSION, this table most use for understanding or interpretation - MP*
CREATE TABLE MEMBERPERMISSION(
MPID int identity primary key,
MPNAME nvarchar(50)
)
GO
-- INSERT MEMBERPERMISSION Table data
INSERT INTO MEMBERPERMISSION (MPNAME) VALUES (N'Administrator')
INSERT INTO MEMBERPERMISSION (MPNAME) VALUES (N'Stuff')
INSERT INTO MEMBERPERMISSION (MPNAME) VALUES (N'Student')
GO
SELECT * FROM MEMBERPERMISSION
GO
-- CREATE TABLE Members - M*
CREATE TABLE MEMBER(
MID int identity primary key,
MUSERNAME nvarchar(32),
MPASSWORD nvarchar(32),
MFULLNAME nvarchar(80),
MADRESS nvarchar(80),
MEMAIL nvarchar(80),
MBIRTHDATE smalldatetime,
MAVARTA image,
MPERMISSION int references MEMBERPERMISSION(MPID)
)
GO
-- INSERT MEMBER
INSERT INTO MEMBER(MUSERNAME,MPASSWORD,MFULLNAME,MADRESS,MEMAIL,MBIRTHDATE,MAVARTA,MPERMISSION)
VALUES (N'admin',N'21232f297a57a5a743894a0e4a801fc3',N'Phạm Huy Đức',N'Long Biên - Hà Nội - Việt Nam',N'ducphgc00103@fpt.edu.vn','08/09/1990',NULL,1)
GO
SELECT * FROM MEMBER
